/*
* (C) Mississippi State University 2009
*
* The WebTOP employs two licenses for its source code, based on the intended use. The core license for WebTOP applications is 
* a Creative Commons GNU General Public License as described in http://*creativecommons.org/licenses/GPL/2.0/. WebTOP libraries 
* and wapplets are licensed under the Creative Commons GNU Lesser General Public License as described in 
* http://creativecommons.org/licenses/*LGPL/2.1/. Additionally, WebTOP uses the same licenses as the licenses used by Xj3D in 
* all of its implementations of Xj3D. Those terms are available at http://www.xj3d.org/licenses/license.html.
*/

package webtop.wsl.event;

/**
 * Objects implementing this interface listen to <code>WSLPlayerEvent</code>s
 * generated by a <code>WSLPlayer</code> to report state transitions.
 *
 * @see			WSLPlayerEvent
 * @see			webtop.wsl.client.WSLPlayer
 *
 * @author	Yong Tze Chi
 */
public interface WSLPlayerListener {
	/**
	 * This method is called by <code>WSLPlayer</code> whenever it changes from
	 * one state to another (e.g., playing to paused).
	 *
	 * @param	 event	information associated with the state transition.
	 */
	public void playerStateChanged(WSLPlayerEvent event);
}
